blockcipher.o: blockcipher.c blockcipher.h error_blockcipher.c error_blockcipher.h
	gcc -c blockcipher.c error_blockcipher.c

error_blockcipher.o: error_blockcipher.c error_blockcipher.h
	gcc -c error_blockcipher.c
	
